// // // // "use client";
// // // import type { Metadata } from "next";
// // // import { Inter } from "next/font/google";
// // // import "./globals.css";
// // // import "bootstrap/dist/css/bootstrap.min.css";
// // // import "primeicons/primeicons.css";
// // // import "primereact/resources/themes/lara-light-cyan/theme.css";
// // // import { Provider } from "react-redux";
// // // import store from "./store/store";
// // // // import { Provider } from "react-redux";
// // // // import store from "./store/store";

// // // const inter = Inter({ subsets: ["latin"] });

// // // export const metadata: Metadata = {
// // //   title: "Create Next App",
// // //   description: "Generated by create next app",
// // // };

// // // export default function RootLayout({
// // //   children,
// // // }: Readonly<{
// // //   children: React.ReactNode;
// // // }>) {
// // //   return (
// // //     <html lang="en">
// // //       <head>
// // //         <link
// // //           rel="stylesheet"
// // //           href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
// // //         />
// // //       </head>
// // //       <body className={inter.className}>
// // //         {/* <Provider store={store}> */}
// // //         <Provider store={store}>{children}</Provider>
// // //         {/* </Provider> */}
// // //       </body>
// // //     </html>
// // //   );
// // // }
// // "use client"; // Add this line to mark the file as a client component

// // import type { Metadata } from "next";
// // import { Inter } from "next/font/google";
// // import "./globals.css";
// // import "bootstrap/dist/css/bootstrap.min.css";
// // import "primeicons/primeicons.css";
// // import "primereact/resources/themes/lara-light-cyan/theme.css";
// // import { Provider } from "react-redux";
// // import store from "./store/store";

// // const inter = Inter({ subsets: ["latin"] });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <head>
// //         <link
// //           rel="stylesheet"
// //           href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
// //         />
// //       </head>
// //       <body className={inter.className}>
// //         {/* The Provider is now wrapped in a Client Component */}
// //         <Provider store={store}>{children}</Provider>
// //       </body>
// //     </html>
// //   );
// // }
// // "use client"; // Keep client-side directive for this file

// // import type { Metadata } from "next";
// // import { Inter } from "next/font/google";
// // import "./globals.css";
// // import "bootstrap/dist/css/bootstrap.min.css";
// // import "primeicons/primeicons.css";
// // import "primereact/resources/themes/lara-light-cyan/theme.css";
// // import { Provider } from "react-redux";
// // import store from "./store/store";
// // // import { metadata } from "./serverLayout"; // Import metadata from server-side layout

// // const inter = Inter({ subsets: ["latin"] });

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <head>
// //         <link
// //           rel="stylesheet"
// //           href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
// //         />
// //       </head>
// //       <body className={inter.className}>
// //         <Provider store={store}>{children}</Provider>
// //       </body>

// //     </html>
// //   );
// // }
'use client';
import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'primeicons/primeicons.css';
import 'primereact/resources/themes/lara-light-cyan/theme.css';
import { Provider } from 'react-redux';
import store from './store/store';
import { ThemeProvider } from './Theme/ThemeContext';
import { usePathname, useRouter } from 'next/navigation';
import Cookies from 'js-cookie';
// import { ThemeProvider } from '@mui/material';
// import theme from './Theme/ThemeComponent';
// import { metadata } from "./serverLayout"; // Import metadata from server-side layout

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: any) {
    const location = usePathname();
    const subdomain = Cookies.get('subdomain');
    const crmaccess = Cookies.get('crmaccess');
    const router = useRouter();

    // Split the path and filter out empty segments
    const pathSegments = location.split('/').filter(Boolean);
    const [location1, location2] = pathSegments;

    // Paths that don't require authentication
    const publicPaths = ['login', 'forgot-password', 'reset-password'];

    if (!crmaccess) {
        // If not authenticated and not already on a public path, redirect to login
        if (!publicPaths.includes(pathSegments[1] || pathSegments[0])) {
            router.push(`/${subdomain || 'flex'}/login`);
        }
    } else {
        // If authenticated but on login page, redirect to dashboard
        if (pathSegments[1] === 'login' || pathSegments[0] === 'login') {
            router.push(`/${subdomain || 'flex'}/dashboard`);
        }
    }
    // else
    // {
    //     window.location.href = `/felxi/login`
    // }
    return (
        <html lang="en">
            <head>
                <title>FlexiCRM</title>
                <meta name="format-detection" content="telephone=no, date=no, email=no, address=no" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link rel="icon" sizes="16x16" href="/logo/favicon-16x16.png" />
                <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet" />
                <link rel="apple-touch-icon" sizes="57x57" href="/logo/apple-icon-57x57.png" />
                <link rel="apple-touch-icon" sizes="60x60" href="/logo/apple-icon-60x60.png" />
                <link rel="apple-touch-icon" sizes="72x72" href="/logo/apple-icon-72x72.png" />
                <link rel="apple-touch-icon" sizes="76x76" href="/logo/apple-icon-76x76.png" />
                <link rel="apple-touch-icon" sizes="114x114" href="/logo/apple-icon-114x114.png" />
                <link rel="apple-touch-icon" sizes="120x120" href="/logo/apple-icon-120x120.png" />
                <link rel="apple-touch-icon" sizes="144x144" href="/logo/apple-icon-144x144.png" />
                <link rel="apple-touch-icon" sizes="152x152" href="/logo/apple-icon-152x152.png" />
                <link rel="apple-touch-icon" sizes="180x180" href="/logo/apple-icon-180x180.png" />
                <link rel="icon" type="image/png" sizes="192x192" href="/logo/android-icon-192x192.png" />
                <link rel="icon" type="image/png" sizes="32x32" href="/logo/favicon-32x32.png" />
                <link rel="icon" type="image/png" sizes="96x96" href="/logo/favicon-96x96.png" />
                <link rel="icon" type="image/png" sizes="16x16" href="/logo/favicon-16x16.png" />
                <link rel="manifest" href="/logo/manifest.json" />
                <meta name="msapplication-TileColor" content="#ffffff" />
                <meta name="msapplication-TileImage" content="/logo/ms-icon-144x144.png" />
                <meta name="theme-color" content="#ffffff"></meta>
            </head>
            <body className={inter.className}>
                <div>
                    <ThemeProvider>
                        <Provider store={store}>{children}</Provider>
                    </ThemeProvider>
                </div>
            </body>
        </html>
    );
}
// src/app/layout.tsx

// import { Inter } from 'next/font/google';
// import './globals.css';
// import 'bootstrap/dist/css/bootstrap.min.css';
// import 'primeicons/primeicons.css';
// import 'primereact/resources/themes/lara-light-cyan/theme.css';
// import { Provider } from 'react-redux';
// import store from './store/store';
// import { ThemeProvider } from './Theme/ThemeContext';

// const inter = Inter({ subsets: ['latin'] });

// export default function RootLayout({ children }: any) {
//     return (
//         <html lang="en">
//             <head>
//                 <meta name="format-detection" content="telephone=no, date=no, email=no, address=no" />
//                 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
//             </head>
//             <body className={inter.className}>
//                 <div>
//                     <ThemeProvider>
//                         <Provider store={store}>{children}</Provider>
//                     </ThemeProvider>
//                 </div>
//             </body>
//         </html>
//     );
// }
