// // // "use client";
// // import type { Metadata } from "next";
// // import { Inter } from "next/font/google";
// // import "./globals.css";
// // import "bootstrap/dist/css/bootstrap.min.css";
// // import "primeicons/primeicons.css";
// // import "primereact/resources/themes/lara-light-cyan/theme.css";
// // import { Provider } from "react-redux";
// // import store from "./store/store";
// // // import { Provider } from "react-redux";
// // // import store from "./store/store";

// // const inter = Inter({ subsets: ["latin"] });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <head>
// //         <link
// //           rel="stylesheet"
// //           href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
// //         />
// //       </head>
// //       <body className={inter.className}>
// //         {/* <Provider store={store}> */}
// //         <Provider store={store}>{children}</Provider>
// //         {/* </Provider> */}
// //       </body>
// //     </html>
// //   );
// // }
// "use client"; // Add this line to mark the file as a client component

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import "bootstrap/dist/css/bootstrap.min.css";
// import "primeicons/primeicons.css";
// import "primereact/resources/themes/lara-light-cyan/theme.css";
// import { Provider } from "react-redux";
// import store from "./store/store";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           rel="stylesheet"
//           href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
//         />
//       </head>
//       <body className={inter.className}>
//         {/* The Provider is now wrapped in a Client Component */}
//         <Provider store={store}>{children}</Provider>
//       </body>
//     </html>
//   );
// }
// "use client"; // Keep client-side directive for this file

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import "bootstrap/dist/css/bootstrap.min.css";
// import "primeicons/primeicons.css";
// import "primereact/resources/themes/lara-light-cyan/theme.css";
// import { Provider } from "react-redux";
// import store from "./store/store";
// // import { metadata } from "./serverLayout"; // Import metadata from server-side layout

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           rel="stylesheet"
//           href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
//         />
//       </head>
//       <body className={inter.className}>
//         <Provider store={store}>{children}</Provider>
//       </body>

//     </html>
//   );
// }
'use client';

import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'primeicons/primeicons.css';
import 'primereact/resources/themes/lara-light-cyan/theme.css';
import { Provider } from 'react-redux';
import store from './store/store';
import { ThemeProvider } from './Theme/ThemeContext';
// import { ThemeProvider } from '@mui/material';
// import theme from './Theme/ThemeComponent';
// import { metadata } from "./serverLayout"; // Import metadata from server-side layout

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: any) {
    return (
        <html lang="en">
            <head>
                <meta name="format-detection" content="telephone=no, date=no, email=no, address=no" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet" />
            </head>
            <body className={inter.className}>
                <div>
                    <ThemeProvider>
                        <Provider store={store}>{children}</Provider>
                    </ThemeProvider>
                </div>
            </body>
        </html>
    );
}
